openapi: 3.0.2
info:
  title: Nøkkeltall fra årsregnskapet
  description: |
    _Dette er et midlertidig API som er utviklet for FoU (Forsknings- og utviklingsarbeid), og særskilt for EUbusinessgraph. APIèt vil ikke bli videreutviklet eller vedlikeholdt, og kan bli lagt ned uten varsel.
    API'et kan brukes av alle, men har dere behov for kontinuerlig oppdatering fra Regnskapsregisteret, anbefaler vi at dere avventer til en fullverdig versjon av API regnskapsregisteret blir publisert i løpet av de nærmeste årene._

    _APIèt inneholder nøkkeltall fra sist innsendte årsregnskap som er godkjent av Regnskapsregisteret, fra og med regnskapsåret 2018.  Dette gjelder for de virksomhetene som følger ordinær oppstillingsplan etter regnskapsloven. Regnskapstall fra f.eks. banker og forsikringsselskap er ikke tilgjengelig. Konserntall er heller ikke tilgjengelig. Dette Api'et inneholder heller ikke opplysninger om hvorvidt virksomheten er slettet, gått konkurs eller annen tilsvarende opplysninger. Disse opplysningene finner dere her: <https://data.brreg.no/enhetsregisteret/oppslag/enheter>_
  version: '1.0.2'
  contact:
    name: Forenkling og Brukerdialog hos Brønnøysundregistrene
    url: 'https://www.brreg.no/'
    email: opendata@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: regnskapsregisteret
    description: Regnskapsregister API
servers:
  - url: 'http://data.brreg.no/regnskapsregisteret/regnskap/'
    description: Server i prodmiljø
  - url: 'http://data.ppe.brreg.no/regnskapsregisteret/regnskap/'
    description: Server i preprod-miljø
paths:
  /regnskapsregisteret/regnskap/{orgNummer}:
    get:
      tags:
        - regnskapsregisteret
      summary: Query for regnskap.
      description: Returnerer en samling årsregnskap
      operationId: getRegnskap
      parameters:
        - name: orgNummer
          in: path
          description: Virksomhetens organisasjonsnummer
          required: true
          schema:
            type: string
        - name: år
          in: query
          description: Hent årsregnskap for spesifikt år
          required: false
          schema:
            type: integer
        - name: regnskapstype
          in: query
          description: Hent årsregnskap for spesifik regnskapstype (selskap eller konsern)
          required: false
          schema:
            $ref: "#/components/schemas/Regnskapstype"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            application/ld+json:
              schema:
                type: object
            application/rdf+json:
              schema:
                type: object
            application/rdf+xml:
              schema:
                type: object
            text/turtle:
              schema:
                type: object
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"

  /regnskapsregisteret/regnskap/{orgNummer}/{id}:
    get:
      tags:
        - regnskapsregisteret
      description: Hent et spesifikt årsregnskap for en virksomhet
      operationId: getRegnskapById
      parameters:
        - name: orgNummer
          in: path
          description: Virksomhetens organisasjonsnummer
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            application/ld+json:
              schema:
                type: object
            application/rdf+json:
              schema:
                type: object
            application/rdf+xml:
              schema:
                type: object
            text/turtle:
              schema:
                type: object
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"

  /regnskapsregisteret/regnskap/log:
    get:
      tags:
        - regnskapsregisteret
      summary: Query for log.
      description: Returnerer en logg over filer som har blitt lastet inn i systemet
      operationId: getLog
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/xml:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"

  /test/most-recent:
    get:
      tags:
        - test
      summary: For testing. Returns most recently imported orgnr
      description: Returnerer det sist importerte orgnr
      operationId: getMostRecent
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"
  /statistikk/by-ip:
    get:
      tags:
        - statistikk
      summary: Query for statisctics, by IP
      description: Returnerer en liste over de mest aktive IP-ene
      operationId: getStatisticsByIp
      parameters:
        - name: fraDato
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: tilDato
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"
  /statistikk/by-orgnr:
    get:
      tags:
        - statistikk
      summary: Query for statisctics, by organization number
      description: Returnerer en liste over de mest søkte organisasjonsnummerene
      operationId: getStatisticsByOrgnr
      parameters:
        - name: fraDato
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: tilDato
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"
  /statistikk/by-method:
    get:
      tags:
        - statistikk
      summary: Query for statisctics, by REST method
      description: Returnerer en liste over kall til de ulike REST-metodene
      operationId: getStatisticsByMethod
      parameters:
        - name: fraDato
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: tilDato
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Feil oppstod
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorRespons"
              examples:
                ServerErrorRespons:
                  $ref: "#/components/examples/ServerErrorRespons"
components:
  schemas:
    Regnskap:
      type: object
      description: Et regnskap for et gitt år
      properties:
        id:
          type: integer
          format: int32
          description: system-generert id
        journalnr:
          type: string
        regnskapstype:
          $ref: "#/components/schemas/Regnskapstype"
        regnskapDokumenttype:
          type: String
        virksomhet:
          $ref: "#/components/schemas/Virksomhet"
        regnskapsperiode:
          $ref: "#/components/schemas/Tidsperiode"
        valuta:
          $ref: "#/components/schemas/Valutakode"
        avviklingsregnskap:
          type: boolean
        oppstillingsplan:
          type: string
          enum:
            - smaa
            - store
            - oevrige
        revisjon:
          $ref: "#/components/schemas/Revisjon"
        regnkapsprinsipper:
          $ref: "#/components/schemas/Regnskapsprinsipper"
        egenkapitalGjeld:
          $ref: "#/components/schemas/EgenkapitalGjeld"
        eiendeler:
          $ref: "#/components/schemas/Eiendeler"
        resultatregnskapResultat:
          $ref: "#/components/schemas/ResultatregnskapResultat"
    ResultatregnskapResultat:
      type: object
      externalDocs:
        description: Begrepsreferanse
        url: https://jira.brreg.no/browse/BEGREP-821
      properties:
        ordinaertResultatFoerSkattekostnad:
          type: number
        ordinaertResultatSkattekostnad:
          type: number
        ekstraordinaerePoster:
          type: number
        skattekostnadEkstraordinaertResultat:
          type: number
        aarsresultat:
          type: number
        totalresultat:
          type: number
        finansresultat:
          $ref: "#/components/schemas/Finansresultat"
        driftsresultat:
          $ref: "#/components/schemas/Driftsresultat"
    EgenkapitalGjeld:
      type: object
      properties:
        sumEgenkapitalGjeld:
          type: number
        egenkapital:
          $ref: "#/components/schemas/Egenkapital"
        gjeldOversikt:
          $ref: "#/components/schemas/Gjeld"
    Eiendeler:
      type: object
      properties:
        goodwill:
          type: number
        sumVarer:
          type: number
        sumFordringer:
          type: number
        sumInvesteringer:
          type: number
        sumBankinnskuddOgKontanter:
          type: number
        sumEiendeler:
          type: number
        omloepsmidler:
          $ref: "#/components/schemas/Omloepsmidler"
        anleggsmidler:
          $ref: "#/components/schemas/Anleggsmidler"
    Anleggsmidler:
      type: object
      properties:
        sumAnleggsmidler:
          type: number
    Omloepsmidler:
      type: object
      properties:
        sumOmloepsmidler:
          type: number
    Finansresultat:
      type: object
      properties:
        nettoFinans:
          type: number
        finansinntekt:
          $ref: "#/components/schemas/Finansinntekt"
        finanskostnad:
          $ref: "#/components/schemas/Finanskostnad"
    Driftsresultat:
      type: object
      properties:
        driftsresultat:
          type: number
        driftsinntekter:
          $ref: "#/components/schemas/Driftsinntekter"
        driftskostnad:
          $ref: "#/components/schemas/Driftskostnad"
    Driftsinntekter:
      type: object
      properties:
        salgsinntekter:
          type: number
        sumDriftsinntekter:
          type: number
    Driftskostnad:
      type: object
      properties:
        loennskostnad:
          type: number
        sumDriftskostnad:
          type: number
    Finansinntekt:
      type: object
      properties:
        sumFinansinntekter:
          type: number
    Finanskostnad:
      type: object
      properties:
        rentekostnadSammeKonsern:
          type: number
        annenRentekostnad:
          type: number
        sumFinanskostnad:
          type: number
    Virksomhet:
      type: object
      description: Virksomheten som regnskapet tilhører
      properties:
        organisasjonsnummer:
          type: string
        organisasjonsform:
          type: string
        morselskap:
          type: boolean
    Tidsperiode:
      type: object
      properties:
        fraDato:
          type: string
          format: date
        tilDato:
          type: string
          format: date
    Valutakode:
      type: string
    Revisjon:
      type: object
      properties:
        ikkeRevidertAarsregnskap:
          type: boolean
        fravalgRevisjon:
          type: boolean
    Regnskapsprinsipper:
      type: object
      properties:
        smaaForetak:
          type: boolean
        regnskapsregler:
          type: string
          enum:
            - IFRS
            - forenkletAnvendelseIFRS
            - regnskapslovenAlminneligRegler
    Egenkapital:
      type: object
      properties:
        sumEgenkapital:
          type: number
        opptjentEgenkapital:
          $ref: "#/components/schemas/OpptjentEgenkapital"
        innskuttEgenkapital:
          $ref: "#/components/schemas/InnskuttEgenkapital"
    OpptjentEgenkapital:
      type: object
      properties:
        sumOpptjentEgenkapital:
          type: number
    InnskuttEgenkapital:
      type: object
      properties:
        sumInnskuttEgenkaptial:
          type: number
    Gjeld:
      type: object
      properties:
        sumGjeld:
          type: number
        kortsiktigGjeld:
          $ref: "#/components/schemas/KortsiktigGjeld"
        langsiktigGjeld:
          $ref: "#/components/schemas/LangsiktigGjeld"
    KortsiktigGjeld:
      type: object
      properties:
        sumKortsiktigGjeld:
          type: number
    LangsiktigGjeld:
      type: object
      properties:
        sumLangsiktigGjeld:
          type: number
    Regnskapstype:
      type: string
      enum:
        - SELSKAP
        - KONSERN
    ServerErrorRespons:
      type: object
      description: Respons for generisk feilmelding
      properties:
        timestamp:
          type: string
          description: Tidspunkt feilen oppstod. Format er ISO-8601
        status:
          type: string
          description: HTTP statuskode for feilmeldingen
        error:
          type: string
          description: HTTP beskrivelse for status
        message:
          type: string
          description: En tekstlig beskrivelse av feilen
        path:
          type: string
          description: Sti til dette endepunktet
        trace:
          type: string
          description: En tilfeldig generert UUID.
  examples:
    ServerErrorRespons:
      summary: Error Respons
      value:
        timestamp: 2021-05-28T11:34:33.435+0000
        status: 500
        error: Internal Server Error
        message: Internal Server Error
        path: /regnskapsregisteret/regnskap/999999999
        trace: 5631709a-6e3e-4b72-94e7-fcbf6341272a
