spring:
  liquibase:        # Disable Liquibase globally, to prevent liquibase instanciating for sybase.
    enabled: false  # Postgres not affected, as it is configured manually to use liquibase
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  endpoints:
    web:
      exposure:
        include: health, prometheus
regnskap:
  update:
    enabled: ${RRAPI_UPDATE_ENABLED:false}
  jena-external-url:
    regnskapsregisteretUrl: ${RRAPI_JENA_EXTERNAL_URL_REGNSKAPSREGISTERET_URL}
    organizationCatalogueUrl: ${RRAPI_JENA_EXTERNAL_URL_ORGANIZATION_CATALOGUE_URL}
  sftp:
    host: ${RRAPI_SFTP_SERVER}
    port: ${RRAPI_SFTP_PORT}
    user: ${RRAPI_SFTP_USER}
    password: ${RRAPI_SFTP_PASSWORD}
    directory: ${RRAPI_SFTP_DIRECTORY}
  slack:
    channel: ${RRAPI_SLACK_CHANNEL}
    token: ${RRAPI_SLACK_TOKEN}
  ip:
    salt: ${RRAPI_IP_SALT}
  aarsregnskap-copy:
    enabled: ${RRAPI_AARSREGNSKAP_COPY_ENABLED:true}
    external-enabled: ${RRAPI_AARSREGNSKAP_COPY_EXTERNAL_ENABLED:false}
    filepath-prefix: ${RRAPI_AARSREGNSKAP_COPY_FILEPATH_PREFIX}
    years-available: ${RRAPI_AARSREGNSKAP_COPY_YEARS_AVAILABLE:15}
    experimental-converter: ${RRAPI_AARSREGNSKAP_COPY_EXPERIMENTAL_CONVERTER:false}
    mellombalanse-enabled: ${RRAPI_AARSREGNSKAP_COPY_MELLOMBALANSE_ENABLED:false}
    sarepta-url: ${RRAPI_AARSREGNSKAP_SAREPTA_URL}
  aardb:
    datasource:
      jdbc-url: ${RRAPI_AARDB_URL}
      username: ${RRAPI_AARDB_USER}
      password: ${RRAPI_AARDB_PASS}
      driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
  rregapidb:
    datasource:
      jdbc-url: ${RRAPI_POSTGRES_DB_URL}
      username: ${RRAPI_POSTGRES_USER}
      password: ${RRAPI_POSTGRES_PASSWORD}
  cache:
    ttl-after-accessed-aar-requests: ${CACHE_TTL_AAR_REQUESTS_SECONDS}
    ttl-after-created-aar-copy-filemeta: ${CACHE_TTL_AAR_COPY_FILEMETA_SECONDS}

bucket4j:
  enabled: true
  cache-to-use: jcache
  filters:
    - cache-name: aarsregnskapCopyBucket
      filter-order: 1000
      url: (/aarsregnskap.*|/regnskapsregisteret/regnskap/aarsregnskap.*)
      rate-limits:
        - cache-key: "getHeader('X-Forwarded-For') != null ? getHeader('X-Forwarded-For').split(',')[0].trim() : getRemoteAddr()"
          bandwidths:
            - id: short
              capacity: ${AARSREGNSKAP_RATE_LIMIT_SHORT_CAPACITY}
              time: ${AARSREGNSKAP_RATE_LIMIT_SHORT_TIME_SECONDS}
              unit: seconds
              refill-speed: interval
            - id: medium
              capacity: ${AARSREGNSKAP_RATE_LIMIT_MEDIUM_CAPACITY}
              time: ${AARSREGNSKAP_RATE_LIMIT_MEDIUM_TIME_SECONDS}
              unit: seconds
              refill-speed: interval
            - id: long
              capacity: ${AARSREGNSKAP_RATE_LIMIT_LONG_CAPACITY}
              time: ${AARSREGNSKAP_RATE_LIMIT_LONG_TIME_SECONDS}
              unit: seconds
              refill-speed: interval

springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /regnskapsregisteret/regnskap/v3/api-docs
  swagger-ui:
    path: /regnskapsregisteret/regnskap/swagger-ui/index.html
    urlsPrimaryName: regnskapsregisteret
