spring:
  liquibase:        # Disable Liquibase globally, to prevent liquibase instanciating for sybase.
    enabled: false  # Postgres not affected, as it is configured manually to use liquibase


postgres:
  rreg:
    db_url: jdbc:postgresql://localhost:5432/regnskap?currentSchema=rregapi&sslmode=prefer
    dbo_user: postgres
    dbo_password: password
    user: postgres
    password: password

regnskap:
  update:
    enabled: ${RRAPI_UPDATE_ENABLED:true}
  jena-external-url:
    regnskapsregisteretUrl: http://data.ppe.brreg.no/regnskapsregisteret/regnskap/%s/%d
    organizationCatalogueUrl: https://publishers-api.ut1.fellesdatakatalog.brreg.no/organizations/
  sftp:
    host: filporten.brreg.no
    port: 22
    user: ${RRAPI_SFTP_USER}
    password: ${RRAPI_SFTP_PASSWORD}
    directory: /out
  slack:
    channel: localhost
    token: disabled
  ip:
    salt: salt
  aarsregnskap-copy:
    enabled: true
    filepathPrefix: ${RRAPI_AARSREGNSKAP_COPY_FILEPATH_PREFIX:src/main/resources/aarsregnskap-mock-files}
  aardb:
    datasource:
      jdbc-url: ${RRAPI_AARDB_URL:jdbc:sybase:Tds:aseavgtest.brreg.no:5005/aardb}
      username: ${RRAPI_AARDB_USER}
      password: ${RRAPI_AARDB_PASS}
      driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
  cache:
    ttl-after-accessed-aar-requests: ${CACHE_TTL_AAR_REQUESTS_SECONDS:86400}
    ttl-after-created-aar-copy-filemeta: ${CACHE_TTL_AAR_COPY_FILEMETA_SECONDS:120}

bucket4j:
  enabled: true
  cache-to-use: jcache
  filters:
    - cache-name: aarsregnskapCopyBucket
      filter-order: 1000
      url: /aarsregnskap.*
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - id: short
              capacity: ${AARSREGNSKAP_RATE_LIMIT_SHORT_CAPACITY:30}
              time: ${AARSREGNSKAP_RATE_LIMIT_SHORT_TIME_SECONDS:30}
              unit: seconds
              refill-speed: interval
            - id: medium
              capacity: ${AARSREGNSKAP_RATE_LIMIT_MEDIUM_CAPACITY:300}
              time: ${AARSREGNSKAP_RATE_LIMIT_MEDIUM_TIME_SECONDS:600}
              unit: seconds
              refill-speed: interval
            - id: long
              capacity: ${AARSREGNSKAP_RATE_LIMIT_LONG_CAPACITY:15000}
              time: ${AARSREGNSKAP_RATE_LIMIT_LONG_TIME_SECONDS:43200} # 12hrs default
              unit: seconds
              refill-speed: interval

springdoc:
  api-docs:
    path: /regnskapsregisteret/regnskap/v3/api-docs
    enabled: true
  swagger-ui:
    path: /regnskapsregisteret/regnskap/swagger-ui/index.html
    url: /regnskapsregisteret/regnskap/v3/api-docs
